schools:
   path: /
   controller: App\Controller\SchoolController::schools

create:
   path: /school/create
   controller: App\Controller\SchoolController::create

update:
   path: /school/update{id}
   controller: App\Controller\SchoolController::update

delete:
   path: /school/delete{id}
   controller: App\Controller\SchoolController::delete
